### PR TITLE
Add cancellable parameter to allow for cancel button on form.

### PR DESCRIPTION
**Pull request by Kelley12**
Wanting to be able to have a cancel button on a form built using quick-form.

### CODE REVIEW

**Comment by drew-y** [comment]
What does the cancel button do?

**Comment by Kelley12** [comment]
In the case of VBXC, it would cancel the editable form and go back to a display form without editable fields.

**Comment by drew-y** [comment]
I think we'd wanna do two things in that case.

1. Add the ability to hide the reset button.
2. Emit a cancel event when the cancel button is pressed.

**Comment by Kelley12** [comment]
I agree with #1 would you suggest handling this the same way as the cancel button is shown?
I will add in the emitting the cancel event and update the pull request.

**Comment by drew-y** [comment]
Yeah, that’s how I would do it.

**Comment by Kelley12** [comment]
Alright, updated with those changes, let me know if there's anything else I should add or change.

**Comment by drew-y** [comment]
One last thing. Could you make resettable default to true? We wanna keep the default behavior the same for now.

**Comment by Kelley12** [comment]
Done, good point

**Pull request merged**
